name: Life_IQA
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - boto3==1.39.2
      - botocore==1.39.2
      - certifi==2025.6.15
      - cffi==2.0.0
      - charset-normalizer==2.0.12
      - click==8.2.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - efficientnet-pytorch==0.7.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - fonttools==4.59.0
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - ipykernel==6.30.1
      - ipython==8.37.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lightning-utilities==0.14.3
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - mixture-of-experts==0.2.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - prettytable==3.16.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.52
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyecharts==2.0.8
      - pygments==2.19.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - send2trash==1.8.3
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - swankit==0.2.4
      - swanlab==0.6.4
      - sympy==1.13.3
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - timm==1.0.15
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchinfo==1.8.0
      - torchmetrics==1.7.3
      - torchvision==0.19.0+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.20.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wrapt==1.17.2
      - yacs==0.1.8

