# For livefv, we recommend use 8 GPUs for reproduction
DATA:
  DATASET: livefb
  BATCH_SIZE: 128
  PATCH_NUM: 40
  CROP_SIZE: (224,224)
SET:
  COUNT: 39810
MODEL:
  TYPE: SWIN
  NAME: production
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 384
    JUERY_NUMS: 6
    NUM_EXPERTS: 2
    TOP_K: 2
    DEPTH: 4
#TRAIN:
#  EPOCHS: 30
#  WARMUP_EPOCHS: 5
#  WEIGHT_DECAY: 0.05
#  BASE_LR: 2e-4
#  WARMUP_LR: 2e-7
#  MIN_LR: 2e-6
#  LR_SCHEDULER:
#    NAME: step
#    DECAY_EPOCHS: 10
#DISABLE_SAVE: True
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.01
  BASE_LR: 2.0e-5
  WARMUP_LR: 2.0e-6
  MIN_LR: 2.0e-6
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 10
DISABLE_SAVE: True
