DATA:
  DATASET: livec
  BATCH_SIZE: 64  
  PATCH_NUM: 50  
  CROP_SIZE: (224,224)
SET:
  COUNT: 1162
MODEL:
  TYPE: SWIN
  NAME: production
  DROP_PATH_RATE: 0.15
  SWIN:
    EMBED_DIM: 384
    JUERY_NUMS: 6
    NUM_EXPERTS: 2
    TOP_K: 2
    DEPTH: 2
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.01
  BASE_LR: 3.0e-5
  WARMUP_LR: 2.0e-7
  MIN_LR: 1.0e-6
  LR_SCHEDULER:
    NAME: cosine
    DECAY_EPOCHS: 20
DISABLE_SAVE: True
